#ifndef CAPTUREIMAGESTCP_GLOBAL_H
#define CAPTUREIMAGESTCP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CAPTUREIMAGESTCP_LIBRARY)
#  define CAPTUREIMAGESTCP_EXPORT Q_DECL_EXPORT
#else
#  define CAPTUREIMAGESTCP_EXPORT Q_DECL_IMPORT
#endif

#endif // CAPTUREIMAGESTCP_GLOBAL_H
