#ifndef DECODINGTHEVIDEO_GLOBAL_H
#define DECODINGTHEVIDEO_GLOBAL_H

#include <QtCore/qglobal.h>
#include <QDebug>

#if defined(DECODINGTHEVIDEO_LIBRARY)
#  define DECODINGTHEVIDEO_EXPORT Q_DECL_EXPORT
#else
#  define DECODINGTHEVIDEO_EXPORT Q_DECL_IMPORT
#endif

#endif // DECODINGTHEVIDEO_GLOBAL_H
