#ifndef CAPTUREIMAGES_UNDERLYING_GLOBAL_H
#define CAPTUREIMAGES_UNDERLYING_GLOBAL_H

#include <QtCore/qglobal.h>
#include <QThread>
#include <QTimer>
#include <QtNetwork/QSctpSocket>

#if defined(CAPTUREIMAGES_UNDERLYING_LIBRARY)
#  define CAPTUREIMAGES_UNDERLYINGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CAPTUREIMAGES_UNDERLYINGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CAPTUREIMAGES_UNDERLYING_GLOBAL_H
