#ifndef DATAPROCESSING_GLOBAL_H
#define DATAPROCESSING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATAPROCESSING_LIBRARY)
#  define DATAPROCESSING_EXPORT Q_DECL_EXPORT
#else
#  define DATAPROCESSING_EXPORT Q_DECL_IMPORT
#endif

#endif // DATAPROCESSING_GLOBAL_H
