#ifndef DATABASEREAD_GLOBAL_H
#define DATABASEREAD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATABASEREAD_LIBRARY)
#  define DATABASEREADSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DATABASEREADSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DATABASEREAD_GLOBAL_H
